sudo: required

services:
  - postgresql

language: python
python:
    - "3.6"

notifications:
  email: false

before_install:
  - source env/environ.env
  - psql -U postgres -c "CREATE USER $DB_USER PASSWORD '$DB_PASS'"
  - psql -U postgres -c "CREATE DATABASE $DB_NAME OWNER $DB_USER"
  - psql -U postgres -c "ALTER ROLE $DB_USER CREATEDB;"
  - pip3 install -r requirements.txt
  - python3 manage.py migrate

script:
  - python3 manage.py test
