sudo: required

services:
  - postgresql
  - redis-server

language: python
python:
    - "3.6"

notifications:
  email: false

before_install:
  - export DB_NAME=ciex_db
  - export DB_USER=ciex
  - export DB_PASS=ciex
  - export DB_PORT=5432
  - export DB_HOST=localhost
  - export REDIS_HOST=redis
  - export REDIS_PORT=6379
  - psql -U postgres -c "CREATE USER $DB_USER PASSWORD '$DB_PASS'"
  - psql -U postgres -c "CREATE DATABASE $DB_NAME OWNER $DB_USER"
  - psql -U postgres -c "ALTER ROLE $DB_USER CREATEDB;"
  - cp env/.env src/.env

install:
  - pip3 install -r src/requirements.txt
  - python3 src/manage.py migrate

script:
  - python3 src/manage.py test src
