# Generated by Django 2.1 on 2018-08-10 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='create_time',
            field=models.TimeField(auto_now_add=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_time',
            field=models.TimeField(blank=True, default=None, null=True, verbose_name='Started'),
        ),
        migrations.AlterField(
            model_name='task',
            name='time_to_execute',
            field=models.TimeField(blank=True, default=None, null=True, verbose_name='Executed'),
        ),
    ]
