# Generated by Django 2.1 on 2018-08-10 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20180810_1904'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='time_to_execute',
            new_name='exec_time',
        ),
    ]
